# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70f85bbe3f526dc6b72b491a77492ce1beaa8c3b4b6078373907461ea7a5602295574ba2f6a05f0d9dc31bd1bebda20226e287f9760537f03f7fb3edb7b027a

test:
  secret_key_base: 6f4952b4b639f0bc335902ca1d85b539b1657003344bff41dda7363f62522f9dad42e90cb5602d0aa57d6f7f6ecc3a0abb6a43dbc0725da3927b71b5fbd759e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
